name: sikilap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.0


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_lucide: ^1.6.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.10.0
  url_strategy: ^0.3.0
  intl: ^0.20.2
  syncfusion_flutter_core: ^29.2.11
  syncfusion_flutter_sliders: ^29.2.11
  flutter_quill: ^11.4.1
  carousel_slider: ^5.0.0
  reorderable_grid: ^1.0.10
  loading_animation_widget: ^1.3.0
  file_picker: ^10.2.0
  syncfusion_flutter_charts: ^29.2.11
  syncfusion_flutter_maps: ^29.2.11
  timelines_plus: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/avatar/
    - assets/lang/
    - assets/images/dummy/
    - assets/images/dummy/map/
    - assets/images/dummy/mitra/
    - assets/images/dummy/room/
    - assets/images/logo/

dependency_overrides:
  file_picker: ^10.2.0
